[metadata]
name    = "storm"
author  = "ave"

[global]
plan    = "storm"
case    = "storm"
builder = "docker:go"
runner  = "cluster:k8s"
total_instances = 800

[global.build_config]
push_registry=true
go_proxy_mode="direct"
registry_type="aws"

[global.run_config]


[[groups]]
id = "first"
instances = { count = 800 }

  [groups.resources]
  memory = '512Mi'
  cpu = '2000m'

  [groups.run.test_params]
  conn_count = '10'
  conn_outgoing = '50'
  conn_delay_ms = '30000'
  concurrent_dials = '1'
  data_size_mb     = '40960'
