[metadata]
name    = "storm"
author  = "ave"

[global]
plan    = "storm"
case    = "storm"
builder = "docker:go"
runner  = "local:docker"
total_instances = 30

[global.build_config]
go_proxy_mode="direct"

[global.run_config]


[[groups]]
id = "first"
instances = { count = 30 }

  [groups.resources]
  memory = '512Mi'
  cpu = '2000m'

  [groups.run.test_params]
  conn_count = '10'
  conn_outgoing = '15'
  conn_delay_ms = '30000'
  concurrent_dials = '2'
  data_size_mb     = '100'
